### ISSUE TITLE
Does this work with Sigrok?

### ISSUE THREAD

**Issue by probonopd** [EUA/ESP32_LogicAnalyzer#1]
https://sigrok.org seems to support the SUMP protocol according to https://sigrok.org/wiki/Category:Sump_protocol, do you think this firmware could work with it?

**Comment by EUA** [comment]
Definitely.
But if you don't apply this [patch](https://sigrok.org/bugzilla/show_bug.cgi?id=1025) to libsigrok, you have to flush your RX buffer. Otherwise pulseview(sigrok) has difficulties for detect it.

Other alternative is using Serial2 as OLS port. Which is faster and easy to live with it. You still need to flush RX buffer at detection but since DTR doesn't reset the ESP32, it's much easier to live with it.

You can change to Serial2 using ESP32_LogicAnalyzer.h
Default speed is 3Mbaud for Serial2, you can change it as your USB-to-TTL cable supported value.
